name: CD

on:
  push:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: JDWorkoutApp/jd_workout_golang
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          dockerfile: ./docker/app/DockerfileCI
          tags: latest
      - name: Publish to Registry Mysql
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: JDWorkoutApp/jd_workout_golang_mysql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          dockerfile: ./docker/mysql/DockerfileCI
          tags: latest
      - name: Publish to Registry Redis
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: JDWorkoutApp/jd_workout_golang_redis
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ghcr.io
          dockerfile: ./docker/redis/DockerfileCI
          tags: latest
      - name: Pull image and deploy, and migrate
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            export PROCESS_TYPE=cd && 
            cd /app/jd_workout_golang && 
            docker-compose pull && 
            docker-compose up -d && 
            docker image prune -f &&
            docker-compose exec -T app /app/migrate migrate
